(function(){
  'use strict';
  const state=document.getElementById('analystState');const grid=document.getElementById('productIdeaGrid');
  const el=(tag,cls,text)=>{const node=document.createElement(tag);if(cls)node.className=cls;if(text!==undefined)node.textContent=text;return node;};const set=(id,value)=>document.getElementById(id).textContent=String(value);
  function stamp(value){if(!value)return 0;if(value.toDate)return value.toDate().getTime();if(value.seconds)return value.seconds*1000;return new Date(value).getTime()||0;}
  async function api(){if(window.ORMABackoffice)return window.ORMABackoffice;await new Promise(resolve=>window.addEventListener('dolopaws-auth-ready',resolve,{once:true}));return window.ORMABackoffice;}
  async function optional(remote,id,fallback){const result=await remote.getArtifact(id);if(result?.ok)return result.data;if(result?.error==='artifact-not-found')return fallback;throw new Error(`Could not load ${id}`);}
  function latest(reviews,ideaId,subjectType){return reviews.filter(item=>item.ideaId===ideaId&&(item.subjectType||'idea')===subjectType).sort((a,b)=>stamp(b.submittedAt)-stamp(a.submittedAt))[0]||null;}
  function source(source){const link=el('a','bo-source-pill',`${source.label} · ${source.checkedAt} ↗`);link.href=source.url;link.target='_blank';link.rel='noopener';link.title=source.supports||'';return link;}
  function investigationBlock(result){const block=el('section','bo-expanded-research');block.append(el('strong','','Expanded investigation'),el('p','',result.conclusion),el('span','bo-impact',`Recommendation: ${result.recommendation}`));const findings=el('ul');for(const item of result.findings||[])findings.append(el('li','',`${item.competitor}: ${item.finding} ORMA inference: ${item.implicationForOrma}`));block.append(findings);const sources=el('div','bo-source-links');for(const item of result.sources||[])sources.append(source(item));block.append(sources,el('small','bo-decision','Research evidence only. No design or implementation authorisation.'));return block;}
  function mockupBlock(result,review){const wrap=el('section','bo-expanded-research bo-designer-prototype');wrap.append(el('span','bo-stream-type','Product Designer · visual prototype'),el('h4','',result.mockupTitle),el('p','',result.userProblem),el('p','bo-decision-next',result.decisionRationale));const prototype=el('div','bo-prototype-mount');if(window.ORMAProductPrototype)window.ORMAProductPrototype.render(prototype,result);wrap.append(prototype);const flow=el('ol');for(const item of result.userFlow||[])flow.append(el('li','',item));wrap.append(el('strong','','User flow'),flow,el('small','bo-decision','Interactive review artifact. It is not implementation code or development approval.'));return wrap;}
  function receiptMessage(receipt,text,isError=false){receipt.textContent=text;receipt.classList.toggle('is-error',isError);}
  async function submit(idea,subjectType,action,note,buttons,receipt){if((action==='investigate-further'||action==='request-mockup-revision')&&!note.trim()){receiptMessage(receipt,'Add the investigation or revision focus in the box above first.',true);return;}buttons.forEach(button=>button.disabled=true);receiptMessage(receipt,'Saving this Analyst decision…');state.textContent='Saving the Analyst decision…';const response=await window.ORMABackoffice.submitAnalystReview({subjectType,ideaId:idea.id,action,note});if(!response?.ok){const message=`Could not save: ${response?.error||'unknown error'}`;state.classList.add('is-error');state.textContent=message;receiptMessage(receipt,message,true);buttons.forEach(button=>button.disabled=false);return;}state.classList.remove('is-error');const saved=`Decision ${response.reviewId} saved. ORMA automation owns the next handoff; do not click again.`;state.textContent=saved;receiptMessage(receipt,saved);window.setTimeout(()=>window.location.reload(),1800);}
  function decisionControls(idea,reviews,investigation,design){
    const ideaReview=latest(reviews,idea.id,'idea');const followupReady=ideaReview?.action==='investigate-further'&&ideaReview.status==='processed'&&!!investigation;const locked=ideaReview&&['queued','processing'].includes(ideaReview.status)||ideaReview?.action==='prioritise'&&ideaReview.status==='processed'||['park','dismiss'].includes(ideaReview?.action)&&ideaReview.status==='processed';const controls=el('div','bo-idea-controls');const note=el('textarea');note.placeholder='Optional focus; required for deeper investigation';note.disabled=!!locked;const actions=el('div','bo-actions');const receiptText=!ideaReview?'Awaiting your evidence decision.':ideaReview.status==='queued'?'Saved in Firestore; ORMA automation will collect it on the next healthy run.':ideaReview.status==='processing'?ideaReview.action==='prioritise'?'Designer is preparing the mock-up.':'Market Opportunity is expanding the investigation.':ideaReview.status==='blocked'?`Blocked: ${ideaReview.error||'See automation health.'}`:followupReady?'Investigation is ready. Decide whether to send it to Designer, park or dismiss.':ideaReview.action==='prioritise'?'Design exploration authorised; implementation remains unauthorised.':`Decision processed: ${ideaReview.action.replace(/-/g,' ')}.`;const receipt=el('small','bo-decision',receiptText);receipt.setAttribute('role','status');receipt.setAttribute('aria-live','polite');const buttons=[];for(const [action,label] of [['prioritise','Send to Designer'],['investigate-further','Investigate further'],['park','Park'],['dismiss','Dismiss']]){const button=el('button','',label);button.disabled=!!locked&&!followupReady;button.addEventListener('click',()=>submit(idea,'idea',action,note.value,buttons,receipt).catch(error=>{state.classList.add('is-error');state.textContent=error.message;receiptMessage(receipt,error.message,true);}));buttons.push(button);actions.append(button);}controls.append(note,actions,receipt);return controls;
  }
  function mockupControls(idea,reviews,design){const review=latest(reviews,idea.id,'mockup');const locked=review&&(['queued','processing'].includes(review.status)||review.status==='processed'&&['approve-mockup-for-developer-brief','reject-mockup'].includes(review.action));const controls=el('div','bo-idea-controls');const note=el('textarea');note.placeholder='Required for a mock-up revision';note.disabled=!!locked;const actions=el('div','bo-actions');const receiptText=!review?'Mock-up needs your decision.':review.status==='queued'?'Saved in Firestore; ORMA automation will collect it on the next healthy run.':review.status==='processing'?'Designer revision is in progress.':review.status==='blocked'?`Blocked: ${review.error||'See automation health.'}`:review.outcome?.status==='developer-handoff-ready'?'Developer handoff is ready. Implementation still needs an explicit scope and Release gate.':review.outcome?.status==='mockup-rejected'?'Mock-up rejected; no Developer handoff.':'Revised mock-up ready for review.';const receipt=el('small','bo-decision',receiptText);receipt.setAttribute('role','status');receipt.setAttribute('aria-live','polite');const buttons=[];for(const [action,label] of [['approve-mockup-for-developer-brief','Approve for Developer brief'],['request-mockup-revision','Request Designer revision'],['reject-mockup','Reject mock-up']]){const button=el('button','',label);button.disabled=!!locked;button.addEventListener('click',()=>submit(idea,'mockup',action,note.value,buttons,receipt).catch(error=>{state.classList.add('is-error');state.textContent=error.message;receiptMessage(receipt,error.message,true);}));buttons.push(button);actions.append(button);}controls.append(note,actions,receipt);return controls;}
  function card(idea,reviews,investigations,designs){const article=el('article','bo-idea-card');const top=el('div','bo-idea-top');const badges=el('div','bo-idea-badges');badges.append(el('span',`bo-impact is-${idea.impact}`,`${idea.impact} impact`),el('span','bo-confidence',`${idea.confidence} confidence`));top.append(el('span','bo-stream-type',idea.category.replace(/-/g,' ')),badges);article.append(top,el('h3','',idea.title));const signal=el('div','bo-idea-section');signal.append(el('strong','','Evidence'),el('p','',idea.signal));const opportunity=el('div','bo-idea-section is-opportunity');opportunity.append(el('strong','','ORMA inference/opportunity'),el('p','',idea.ormaOpportunity));article.append(signal,opportunity,el('p','bo-idea-why',idea.whyNow));const sources=el('div','bo-source-links');for(const item of idea.sources||[])sources.append(source(item));article.append(sources);const investigation=investigations.filter(item=>item.ideaId===idea.id).sort((a,b)=>String(b.generatedAt).localeCompare(String(a.generatedAt)))[0];const design=designs.filter(item=>item.ideaId===idea.id).sort((a,b)=>String(b.generatedAt).localeCompare(String(a.generatedAt)))[0];if(investigation)article.append(investigationBlock(investigation));article.append(decisionControls(idea,reviews,investigation,design));if(design)article.append(mockupBlock(design),mockupControls(idea,reviews,design));return article;}
  async function load(){const remote=await api();const [packet,reviewsResult,investigations,designs,status,jobsResult]=await Promise.all([optional(remote,'product-ideas',null),remote.getAnalystReviews(),optional(remote,'product-investigation-results',{items:[]}),optional(remote,'product-design-results',{items:[]}),optional(remote,'strategy-cycle-status',{}),remote.getRevisionJobs()]);if(!packet)throw new Error('No protected Analyst packet exists yet.');if(!reviewsResult?.ok)throw new Error('Could not load Analyst decisions.');if(!jobsResult?.ok)throw new Error('Could not load Analyst jobs.');const reviews=reviewsResult.reviews||[];grid.replaceChildren(...(packet.ideas||[]).map(idea=>card(idea,reviews,investigations.items||[],designs.items||[])));const waiting=(packet.ideas||[]).filter(idea=>!latest(reviews,idea.id,'idea')).length;set('ideaReviewCount',waiting);set('ideaHighImpactCount',(packet.ideas||[]).filter(idea=>idea.impact==='high').length);set('ideaResearchJobs',(jobsResult.jobs||[]).filter(job=>String(job.jobType||'').startsWith('hosted-product')&&['queued','running'].includes(job.status)).length);set('ideaMockups',(designs.items||[]).length);document.getElementById('ideaExecutiveSummary').textContent=packet.executiveSummary||'';state.classList.toggle('is-error',status.status==='failed'||String(status.summary?.productStatus||'').startsWith('blocked:'));state.textContent=String(status.summary?.productStatus||'').startsWith('blocked:')?`Analyst refresh ${status.summary.productStatus}`:`${waiting} of ${(packet.ideas||[]).length} opportunities need a first CEO decision. Sources distinguish evidence from ORMA inference.`;}
  load().catch(error=>{state.classList.add('is-error');state.textContent=error.message;});
})();
