(function(){
  'use strict';
  const state=document.getElementById('designState');const grid=document.getElementById('designGrid');const empty=document.getElementById('designEmpty');
  const el=(tag,cls,text)=>{const node=document.createElement(tag);if(cls)node.className=cls;if(text!==undefined)node.textContent=text;return node;};const set=(id,value)=>document.getElementById(id).textContent=String(value);
  function stamp(value){if(!value)return 0;if(value.toDate)return value.toDate().getTime();if(value.seconds)return value.seconds*1000;return new Date(value).getTime()||0;}
  function displayDate(value){const time=stamp(value);return time?new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeStyle:'short'}).format(time):'Date unavailable';}
  async function api(){if(window.ORMABackoffice)return window.ORMABackoffice;await new Promise(resolve=>window.addEventListener('dolopaws-auth-ready',resolve,{once:true}));return window.ORMABackoffice;}
  async function optional(remote,id,fallback){const result=await remote.getArtifact(id);if(result?.ok)return result.data;if(result?.error==='artifact-not-found')return fallback;throw new Error(`Could not load ${id}`);}
  function latestReview(reviews,ideaId){return reviews.filter(item=>item.ideaId===ideaId&&item.subjectType==='mockup').sort((a,b)=>stamp(b.submittedAt)-stamp(a.submittedAt))[0]||null;}
  function latestDesigns(items){const byIdea=new Map();for(const design of items||[]){const current=byIdea.get(design.ideaId);if(!current||stamp(design.generatedAt)>=stamp(current.generatedAt))byIdea.set(design.ideaId,design);}return [...byIdea.values()].sort((a,b)=>stamp(b.generatedAt)-stamp(a.generatedAt));}
  function list(label,items){const section=el('section','bo-design-detail');section.append(el('strong','',label));const values=items||[];if(!values.length){section.append(el('p','bo-muted','Not supplied in this version.'));return section;}const ul=el('ul');for(const item of values)ul.append(el('li','',typeof item==='string'?item:item.label||item.text||JSON.stringify(item)));section.append(ul);return section;}
  function receiptText(review){if(!review)return 'Prototype needs your visual decision.';if(review.status==='queued')return 'Decision saved in Firestore; ORMA automation will collect it on the next healthy run.';if(review.status==='processing')return review.action==='request-mockup-revision'?'Product Designer revision is in progress.':'The saved decision is being processed.';if(review.status==='blocked')return `Blocked: ${review.error||'See automation health.'}`;if(review.outcome?.status==='developer-handoff-ready')return 'Developer handoff is ready. Implementation still requires an explicit scope and Release gate.';if(review.outcome?.status==='mockup-rejected')return 'Prototype rejected; no Developer handoff was created.';if(review.action==='request-mockup-revision')return 'A revised prototype is ready for review.';return `Decision processed: ${String(review.action||'saved').replace(/-/g,' ')}.`;}
  function isLocked(review){return !!review&&(['queued','processing'].includes(review.status)||(review.status==='processed'&&['approve-mockup-for-developer-brief','reject-mockup'].includes(review.action)));}
  function receiptMessage(receipt,text,isError=false){receipt.textContent=text;receipt.classList.toggle('is-error',isError);}
  async function submit(design,action,note,buttons,receipt){if(action==='request-mockup-revision'&&!note.trim()){receiptMessage(receipt,'Describe what the Product Designer should change first.',true);return;}buttons.forEach(button=>button.disabled=true);receiptMessage(receipt,'Saving this Design decision…');state.textContent='Saving the Design decision…';const response=await window.ORMABackoffice.submitAnalystReview({subjectType:'mockup',ideaId:design.ideaId,action,note});if(!response?.ok){const message=`Could not save: ${response?.error||'unknown error'}`;state.classList.add('is-error');state.textContent=message;receiptMessage(receipt,message,true);buttons.forEach(button=>button.disabled=false);return;}state.classList.remove('is-error');const saved=`Decision ${response.reviewId} saved. ORMA automation owns the next handoff; do not click again.`;state.textContent=saved;receiptMessage(receipt,saved);window.setTimeout(()=>window.location.reload(),1800);}
  function controls(design,review){const locked=isLocked(review);const controls=el('section','bo-design-controls');controls.append(el('h4','','Your prototype decision'));const note=el('textarea');note.placeholder='Required when requesting a Designer revision';note.disabled=locked;const actions=el('div','bo-actions');const receipt=el('small','bo-decision',receiptText(review));receipt.setAttribute('role','status');receipt.setAttribute('aria-live','polite');const buttons=[];for(const [action,label] of [['approve-mockup-for-developer-brief','Approve for Developer brief'],['request-mockup-revision','Request Designer revision'],['reject-mockup','Reject prototype']]){const button=el('button','',label);button.disabled=locked;button.addEventListener('click',()=>submit(design,action,note.value,buttons,receipt).catch(error=>{state.classList.add('is-error');state.textContent=error.message;receiptMessage(receipt,error.message,true);}));buttons.push(button);actions.append(button);}controls.append(note,actions,receipt);return controls;}
  function card(design,idea,review,versionCount){const article=el('article','bo-design-review-card');article.id=`design-${design.ideaId}`;const head=el('header','bo-design-review-head');const title=el('div');title.append(el('span','bo-stream-type',`${idea?.category?idea.category.replace(/-/g,' '):'Product concept'} · version ${versionCount}`),el('h3','',design.mockupTitle||idea?.title||'Untitled prototype'),el('p','',design.userProblem||idea?.ormaOpportunity||''));const status=el('div','bo-design-status');status.append(el('span',isLocked(review)?'bo-life-status is-running':'bo-life-status',isLocked(review)?'Decision saved':'Needs review'),el('small','',`Prepared ${displayDate(design.generatedAt)}`));head.append(title,status);article.append(head);const canvas=el('section','bo-design-canvas');canvas.append(el('div','bo-design-canvas-label','Interactive screen prototype'));const mount=el('div','bo-prototype-mount');if(window.ORMAProductPrototype)window.ORMAProductPrototype.render(mount,design);else mount.append(el('p','bo-state is-error','Prototype renderer did not load.'));canvas.append(mount);article.append(canvas);const rationale=el('div','bo-design-rationale');const summary=el('section','bo-design-detail');summary.append(el('strong','','Why this direction'),el('p','',design.decisionRationale||'No rationale supplied.'));rationale.append(summary,list('User flow',design.userFlow),list('Success criteria',design.successCriteria),list('Constraints',design.constraints),list('Implementation notes',design.implementationNotes));article.append(rationale,controls(design,review));return article;}
  async function load(){const remote=await api();const [ideasPacket,designPacket,reviewsResult,jobsResult]=await Promise.all([optional(remote,'product-ideas',{ideas:[]}),optional(remote,'product-design-results',{items:[]}),remote.getAnalystReviews(),remote.getRevisionJobs()]);if(!reviewsResult?.ok)throw new Error('Could not load Design decisions.');if(!jobsResult?.ok)throw new Error('Could not load Design handoffs.');const designs=latestDesigns(designPacket.items||[]);const reviews=reviewsResult.reviews||[];const ideas=new Map((ideasPacket.ideas||[]).map(idea=>[idea.id,idea]));const versionCounts=new Map();for(const item of designPacket.items||[])versionCounts.set(item.ideaId,(versionCounts.get(item.ideaId)||0)+1);grid.replaceChildren(...designs.map(design=>card(design,ideas.get(design.ideaId),latestReview(reviews,design.ideaId),versionCounts.get(design.ideaId)||1)));empty.hidden=designs.length>0;const pending=designs.filter(design=>!isLocked(latestReview(reviews,design.ideaId))).length;const revisions=reviews.filter(review=>review.subjectType==='mockup'&&review.action==='request-mockup-revision'&&['queued','processing'].includes(review.status)).length;const handoffs=(jobsResult.jobs||[]).filter(job=>job.jobType==='product-development-handoff'&&job.status==='ready-for-review').length;set('designPrototypeCount',designs.length);set('designDecisionCount',pending);set('designRevisionCount',revisions);set('designHandoffCount',handoffs);state.textContent=designs.length?`${pending} of ${designs.length} latest prototypes need a visual decision.`:'No Product Designer prototype exists yet. Start from an evidence-backed Analyst opportunity.';}
  load().catch(error=>{state.classList.add('is-error');state.textContent=error.message;});
})();
