(function(){
  'use strict';
  const state=document.getElementById('editorialState');const grid=document.getElementById('editorialGrid');
  const edited=new Map();
  const el=(tag,cls,text)=>{const node=document.createElement(tag);if(cls)node.className=cls;if(text!==undefined)node.textContent=text;return node;};
  const set=(id,value)=>{const node=document.getElementById(id);if(node)node.textContent=String(value);};
  function stamp(value){if(!value)return 0;if(value.toDate)return value.toDate().getTime();if(value.seconds)return value.seconds*1000;return new Date(value).getTime()||0;}
  async function remote(){if(window.ORMABackoffice)return window.ORMABackoffice;await new Promise(resolve=>window.addEventListener('dolopaws-auth-ready',resolve,{once:true}));if(!window.ORMABackoffice)throw new Error('Protected backoffice connection unavailable');return window.ORMABackoffice;}
  async function optional(api,id,fallback){const result=await api.getArtifact(id);if(result?.ok)return result.data;if(result?.error==='artifact-not-found')return fallback;throw new Error(`Could not load ${id}`);}
  function textFromHtml(value){const template=document.createElement('template');template.innerHTML=String(value||'');const root=template.content.firstElementChild;if(root?.tagName==='META')return root.getAttribute('content')||'';return template.content.textContent.trim();}
  function htmlWithText(original,text){const template=document.createElement('template');template.innerHTML=String(original||'').trim();const root=template.content.firstElementChild;if(root&&template.content.childElementCount===1){if(root.tagName==='META')root.setAttribute('content',text);else root.textContent=text;return root.outerHTML;}return text;}
  function proposal(packet){let html=packet.subject?.original||'';for(const output of packet.outputs||[]){if(output.agentId!=='copywriter'||output.status!=='ready-for-review')continue;(output.result?.changes||[]).forEach((change,index)=>{const after=edited.get(`${packet.generatedAt}:${output.jobId}:${index}`)??change.after;html=html.replace(change.before,after);});}return html;}
  function latestFor(packet,reviews){return reviews.filter(review=>review.packetGeneratedAt===packet.generatedAt&&review.sourceRef===packet.subject?.sourceRef).sort((a,b)=>stamp(b.submittedAt)-stamp(a.submittedAt))[0]||null;}
  function receiptFor(review,receipts){return review?(receipts||[]).find(item=>item.reviewId===review.id)||review.outcome:null;}
  function receiptCopy(review,receipt){
    if(!review)return 'Awaiting your decision.';
    if(review.status==='queued')return 'Decision saved in Firestore. ORMA automation will collect it on the next healthy run; do not click again.';
    if(review.status==='processing')return review.action==='approve'?'Automation is validating and publishing your exact edits.':'The Copywriter revision is in progress.';
    if(review.status==='blocked')return `Action required: ${review.error||receipt?.failureMessage||'The handoff was blocked.'}`;
    if(receipt?.status==='published')return `Published in commit ${String(receipt.commit||'').slice(0,7)}. Website deployment was triggered.`;
    if(receipt?.status==='revision-ready')return 'Revision completed. The new packet will appear as a fresh comparison.';
    return 'Decision processed. The durable receipt is saved.';
  }
  function sourceLinks(output){const links=el('div','bo-source-links');for(const source of output?.result?.sources||[]){const link=el('a','bo-source-pill',`${source.label} · ${source.checkedAt||'date unavailable'} ↗`);link.href=source.url;link.target='_blank';link.rel='noopener';link.title=source.supports||'';links.append(link);}return links;}
  function renderPacket(packet,index,reviews,receipts){
    const review=latestFor(packet,reviews);const receipt=receiptFor(review,receipts);const locked=review&&['queued','processing','processed'].includes(review.status);
    const card=el('article','bo-content-result is-ready-for-review');card.id=`editorial-${packet.subject?.id||index}`;
    const head=el('div','bo-content-head');const intro=el('div');intro.append(el('p','eyebrow',`Packet ${index+1} of 3`),el('h2','',packet.outputs?.[0]?.result?.title||packet.subject?.id||'Guide review'),el('p','',packet.outputs?.[0]?.result?.summary||packet.subject?.sourceRef||''));const status=el('span',`bo-content-status ${locked?'is-processing':'is-ready'}`,locked?String(review.status).replace(/-/g,' '):'Ready for review');head.append(intro,status);card.append(head);
    const compare=el('div','bo-editorial-compare');const current=el('figure');current.append(el('figcaption','','Current page'));const currentFrame=el('iframe');currentFrame.title='Current guide page';currentFrame.sandbox='';currentFrame.srcdoc=packet.subject?.original||'';current.append(currentFrame);const proposed=el('figure');proposed.append(el('figcaption','','Proposed page · updates as you edit'));const proposedFrame=el('iframe');proposedFrame.title='Proposed guide page';proposedFrame.sandbox='';proposedFrame.srcdoc=proposal(packet);proposed.append(proposedFrame);compare.append(current,proposed);card.append(compare);
    const copy=packet.outputs?.find(output=>output.agentId==='copywriter'&&output.status==='ready-for-review');
    for(const [changeIndex,change] of (copy?.result?.changes||[]).entries()){
      const editor=el('div','bo-copy-editor');const label=el('label','',change.section);const textarea=el('textarea');textarea.value=textFromHtml(change.after);textarea.disabled=!!locked;textarea.setAttribute('aria-label',`Edit proposed ${change.section}`);textarea.addEventListener('input',()=>{edited.set(`${packet.generatedAt}:${copy.jobId}:${changeIndex}`,htmlWithText(change.after,textarea.value));proposedFrame.srcdoc=proposal(packet);});editor.append(label,el('small','',`Current: ${textFromHtml(change.before)}`),textarea,el('small','',change.reason));card.append(editor);
    }
    card.append(sourceLinks(copy));
    const controls=el('div','bo-idea-controls');const note=el('textarea');note.placeholder='Required for a revision request';note.disabled=!!locked;const actions=el('div','bo-actions');
    const submit=async action=>{if(action==='request-revision'&&!note.value.trim()){note.focus();state.textContent='Add the exact revision instruction first.';return;}if(action==='approve'&&!window.confirm('Approve this exact edited copy for validation, commit to main and website deployment?'))return;actions.querySelectorAll('button').forEach(button=>button.disabled=true);state.textContent='Saving your decision in protected Firestore…';const edits=copy?[{jobId:copy.jobId,afterByIndex:(copy.result?.changes||[]).map((change,i)=>edited.get(`${packet.generatedAt}:${copy.jobId}:${i}`)??change.after)}]:[];const result=await window.ORMABackoffice.submitEditorialReview({packetGeneratedAt:packet.generatedAt,sourceRef:packet.subject.sourceRef,action,note:note.value,edits});if(!result?.ok){state.classList.add('is-error');state.textContent=`Could not save: ${result?.error||'unknown error'}`;actions.querySelectorAll('button').forEach(button=>button.disabled=false);return;}state.classList.remove('is-error');state.textContent=`Decision ${result.reviewId} saved. ORMA automation now owns validation or revision; do not click again.`;window.setTimeout(()=>window.location.reload(),1800);};
    [['approve','Approve edited copy'],['request-revision','Request Copywriter revision']].forEach(([action,label])=>{const button=el('button',action==='approve'?'bo-primary-action':'',label);button.disabled=!!locked;button.addEventListener('click',()=>submit(action).catch(error=>{state.classList.add('is-error');state.textContent=error.message;}));actions.append(button);});controls.append(note,actions,el('small','bo-decision',receiptCopy(review,receipt)));card.append(controls);return card;
  }
  async function load(){
    const api=await remote();const packetResults=await Promise.all([1,2,3].map(slot=>optional(api,`editorial-review-packet-${slot}`,null)));const [reviewResult,receiptArtifact,statusArtifact]=await Promise.all([api.getEditorialReviews(),optional(api,'editorial-publication-receipts',{receipts:[]}),optional(api,'strategy-cycle-status',{})]);if(!reviewResult?.ok)throw new Error(`Could not load Editorial decisions: ${reviewResult?.error||'unknown error'}`);
    const packets=packetResults.filter(packet=>(packet?.outputs||[]).some(output=>output.status==='ready-for-review'));const reviews=reviewResult.reviews||[];const receipts=receiptArtifact.receipts||[];grid.replaceChildren(...packets.map((packet,index)=>renderPacket(packet,index,reviews,receipts)));
    const waiting=packets.filter(packet=>!latestFor(packet,reviews)).length;const withAutomation=reviews.filter(review=>['queued','processing'].includes(review.status)).length;set('editorialActive',packets.length);set('editorialWaiting',waiting);set('editorialAutomation',withAutomation);set('editorialPublished',receipts.filter(item=>item.status==='published').length);
    if(!packets.length)grid.append(el('p','bo-decision-empty','No guide copy packet is waiting. The Wednesday strategy cycle will refill empty slots.'));
    state.classList.toggle('is-error',statusArtifact.status==='failed');state.textContent=statusArtifact.status==='failed'?`Weekly refresh failed: ${statusArtifact.lastFailure?.message||'Unknown failure'}`:`${waiting} of ${packets.length} active copy packets need your decision. Saved handoffs remain visible after refresh.`;
  }
  load().catch(error=>{state.classList.add('is-error');state.textContent=error.message;});
})();
