(function(){
  'use strict';
  const state=document.getElementById('newsletterState');const metrics=document.getElementById('newsletterInputs');const draft=document.getElementById('newsletterDraft');
  const el=(tag,cls,text)=>{const node=document.createElement(tag);if(cls)node.className=cls;if(text!==undefined)node.textContent=text;return node;};
  function stamp(value){if(!value)return 0;if(value.toDate)return value.toDate().getTime();if(value.seconds)return value.seconds*1000;return new Date(value).getTime()||0;}
  async function api(){if(window.ORMABackoffice)return window.ORMABackoffice;await new Promise(resolve=>window.addEventListener('dolopaws-auth-ready',resolve,{once:true}));return window.ORMABackoffice;}
  async function optional(remote,id,fallback){const result=await remote.getArtifact(id);if(result?.ok)return result.data;if(result?.error==='artifact-not-found')return fallback;throw new Error(`Could not load ${id}`);}
  function renderMetrics(inputs,ready,approved){metrics.replaceChildren();for(const [label,value] of [['New published trails',(inputs.newlyPublishedTrails||[]).length],['Published guide changes',(inputs.publishedEditorialChanges||[]).length],['Current signals',(inputs.timelySafetySignals||[]).length+(inputs.currentEditorialSignals||[]).length],['Approved handoffs',approved]]){const card=el('article');card.append(el('strong','',value),el('span','',label));metrics.append(card);}}
  function issue(result){const preview=el('div','bo-newsletter-preview');const subjects=el('section','bo-newsletter-subjects');subjects.append(el('strong','','Subject options'));const list=el('ol');for(const subject of result.subjectOptions||[])list.append(el('li','',subject));subjects.append(list);preview.append(subjects);const body=el('article','bo-newsletter-issue');body.append(el('span','bo-newsletter-preheader',result.preheader),el('h4','',result.issueTitle),el('p','bo-newsletter-intro',result.introduction));for(const section of result.sections||[]){const block=el('section');block.append(el('h5','',section.heading),el('p','',section.body));if(section.linkUrl){const link=el('a','bo-source-pill','Open linked ORMA page ↗');link.href=section.linkUrl;link.target='_blank';link.rel='noopener';block.append(link);}body.append(block);}body.append(el('p','bo-newsletter-closing',result.closing));preview.append(body);const sources=el('details','bo-newsletter-sources');sources.append(el('summary','',`${(result.sources||[]).length} checked sources`));const links=el('div','bo-source-links');for(const source of result.sources||[]){const link=el('a','bo-source-pill',`${source.label} · ${source.checkedAt} ↗`);link.href=source.url;link.target='_blank';link.rel='noopener';link.title=source.supports;links.append(link);}sources.append(links);preview.append(sources);return preview;}
  async function load(){
    const remote=await api();const [packet,inputs,reviewsResult,approved,status]=await Promise.all([optional(remote,'newsletter-review-packet',null),optional(remote,'newsletter-inputs',{newlyPublishedTrails:[],publishedEditorialChanges:[],timelySafetySignals:[],currentEditorialSignals:[]}),remote.getNewsletterReviews(),optional(remote,'approved-newsletters',{issues:[]}),optional(remote,'strategy-cycle-status',{})]);if(!reviewsResult?.ok)throw new Error('Could not load Newsletter decisions.');const reviews=reviewsResult.reviews||[];const output=(packet?.outputs||[]).find(item=>item.status==='ready-for-review');renderMetrics(inputs,!!output,(approved.issues||[]).length);draft.replaceChildren();
    if(!packet||!output){draft.append(el('p','bo-decision-empty','No complete issue is waiting. The Wednesday strategy cycle will generate one when the 14-day cadence is due.'));state.classList.toggle('is-error',status.status==='failed');state.textContent=status.status==='failed'?`Strategy cycle failed: ${status.lastFailure?.message||'unknown failure'}`:'No Newsletter decision needs you now.';return;}
    const review=reviews.filter(item=>item.packetGeneratedAt===packet.generatedAt).sort((a,b)=>stamp(b.submittedAt)-stamp(a.submittedAt))[0]||null;const locked=review&&['queued','processing','processed'].includes(review.status);const card=el('article',`bo-idea-card${locked?' is-decided':''}`);card.append(el('span','bo-stream-type',`Issue · ${packet.subject?.id||packet.generatedAt.slice(0,10)}`),el('h3','',output.result.issueTitle||'Newsletter issue'),issue(output.result));const note=el('textarea');note.placeholder='Required for a revision request';note.disabled=!!locked;const actions=el('div','bo-actions');
    const submit=async action=>{if(action==='request-revision'&&!note.value.trim()){note.focus();state.textContent='Add one exact revision note first.';return;}actions.querySelectorAll('button').forEach(button=>button.disabled=true);state.textContent='Saving the Newsletter decision…';const response=await window.ORMABackoffice.submitNewsletterReview({packetGeneratedAt:packet.generatedAt,action,note:note.value});if(!response?.ok){state.classList.add('is-error');state.textContent=`Could not save: ${response?.error||'unknown error'}`;actions.querySelectorAll('button').forEach(button=>button.disabled=false);return;}state.textContent=`Decision ${response.reviewId} saved. ORMA automation owns the handoff; do not click again.`;window.setTimeout(()=>window.location.reload(),1800);};
    for(const [action,label] of [['approve','Approve issue for handoff'],['request-revision','Request immediate revision']]){const button=el('button',action==='approve'?'bo-primary-action':'',label);button.disabled=!!locked;button.addEventListener('click',()=>submit(action).catch(error=>{state.classList.add('is-error');state.textContent=error.message;}));actions.append(button);}const receipt=review?review.status==='queued'?'Saved in Firestore; ORMA automation will collect it on the next healthy run.':review.status==='processing'?'Newsletter revision is in progress.':review.status==='blocked'?`Blocked: ${review.error||'See automation health.'}`:review.outcome?.status==='approved-for-social-handoff'?'Approved for Social/future sending; nothing was sent.':review.outcome?.status==='revision-ready'?'Revision ready; reload shows the new issue.':'Decision processed.':'Awaiting your decision.';const controls=el('div','bo-idea-controls');controls.append(note,actions,el('small','bo-decision',receipt));card.append(controls);draft.append(card);state.textContent=locked?'Your decision receipt is visible below the issue.':'One complete issue is ready for your review.';
  }
  load().catch(error=>{state.classList.add('is-error');state.textContent=error.message;});
})();
