'use strict';

const {ingestNewsletterReviews,processNewsletterJobs}=require('./workflows/hosted-newsletter');
const {ingestAnalystReviews,processAnalystJobs}=require('./workflows/hosted-analyst');

const at='2026-08-20T12:00:00.000Z';
function newsletter(generatedAt=at){return {contractVersion:'1.0.0',generatedAt,mode:'draft-only',publicMutationAllowed:false,subject:{type:'newsletter',id:'issue-2026-08-20'},outputs:[{jobId:'newsletter-copy',agentId:'copywriter',status:'ready-for-review',result:{issueTitle:'Mountain days'}}],summary:{readyForReview:1,blocked:0}};}
function product(){return {contractVersion:'1.0.0',generatedAt:at,ideas:[{id:'dog-weather',category:'feature',title:'Dog weather',signal:'Competitor signal',ormaOpportunity:'Dog heat overlay',whyNow:'Summer',impact:'high',confidence:'medium',suggestedInvestigation:['Benchmark'],sources:[]}]};}
function memoryStore(seed={}){const artifacts={...seed};const jobs=[];const newsletterReviews=[];const analystReviews=[];return {artifacts,jobs,newsletterReviews,analystReviews,getArtifact:async id=>artifacts[id]||null,setArtifact:async(id,value)=>{artifacts[id]=value;},putJob:async job=>jobs.push(job),putJobIfAbsent:async job=>{if(jobs.some(item=>item.id===job.id))return false;jobs.push(job);return true;},listJobs:async statuses=>jobs.filter(job=>statuses.includes(job.status)),claimJob:async(id,workerId)=>{const job=jobs.find(item=>item.id===id&&item.status==='queued');if(!job)return null;job.status='running';return {...job,workerId};},completeSystemJob:async(id,fields)=>Object.assign(jobs.find(item=>item.id===id),fields,{status:'completed'}),failJob:async(id,error)=>Object.assign(jobs.find(item=>item.id===id),{status:'queued',systemFailures:1,lastError:error.message}),listNewsletterReviews:async()=>newsletterReviews,markNewsletterReview:async(id,status,fields)=>Object.assign(newsletterReviews.find(item=>item.id===id),{status,...fields}),listAnalystReviews:async()=>analystReviews,markAnalystReview:async(id,status,fields)=>Object.assign(analystReviews.find(item=>item.id===id),{status,...fields})};}

describe('hosted Newsletter',()=>{
  test('approval produces a truthful handoff receipt and never claims sending',async()=>{const store=memoryStore({'newsletter-review-packet':newsletter()});store.newsletterReviews.push({id:'newsletter-1',packetGeneratedAt:at,action:'approve',note:'',submittedAt:at,submittedBy:'moderator'});const outcomes=await ingestNewsletterReviews(store);expect(outcomes).toEqual([expect.objectContaining({status:'processed',sendingStatus:'not-connected'})]);expect(store.artifacts['approved-newsletters'].issues[0]).toEqual(expect.objectContaining({status:'approved-for-social-handoff',sendingStatus:'not-connected',socialStatus:'launch-gated',publicMutationAllowed:false}));expect(store.jobs).toEqual([]);});
  test('revision runs immediately through the agent queue and returns one complete issue',async()=>{const store=memoryStore({'newsletter-review-packet':newsletter(),'newsletter-inputs':{status:'ready'}});store.newsletterReviews.push({id:'newsletter-2',packetGeneratedAt:at,action:'request-revision',note:'Shorter opening.',submittedAt:at});await ingestNewsletterReviews(store);const revised=newsletter('2026-08-20T12:05:00.000Z');const outcomes=await processNewsletterJobs(store,{workerId:'worker',runNewsletter:async()=>revised});expect(outcomes[0].status).toBe('revision-ready');expect(store.artifacts['newsletter-review-packet'].generatedAt).toBe(revised.generatedAt);expect(store.newsletterReviews[0].status).toBe('processed');});
});

describe('hosted Analyst',()=>{
  test('priority passes the CEO direction to Designer but not implementation authority',async()=>{const store=memoryStore({'product-ideas':product()});store.analystReviews.push({id:'analyst-1',subjectType:'idea',ideaId:'dog-weather',action:'prioritise',note:'Focus on heat.',submittedAt:at,submittedBy:'moderator'});await ingestAnalystReviews(store);expect(store.jobs[0]).toEqual(expect.objectContaining({jobType:'hosted-product-design',focus:'Focus on heat.',implementationAuthorized:false,humanGate:'ceo-mockup-approval'}));const mockup={contractVersion:'1.0.0',ideaId:'dog-weather',generatedAt:'2026-08-20T12:05:00Z',mode:'design-review-only',implementationAuthorized:false,publicMutationAllowed:false,mockupTitle:'Heat overlay',screens:[],userFlow:[]};const outcomes=await processAnalystJobs(store,{workerId:'worker',runProductDesigner:async(_idea,focus)=>{expect(focus).toBe('Focus on heat.');return mockup;}});expect(outcomes[0].status).toBe('mockup-ready');expect(store.artifacts['product-design-results'].items[0].implementationAuthorized).toBe(false);});
  test('explicit mock-up approval creates only a gated Developer handoff',async()=>{const mockup={ideaId:'dog-weather',generatedAt:'2026-08-20T12:05:00Z',implementationAuthorized:false};const store=memoryStore({'product-ideas':product(),'product-design-results':{items:[mockup]}});store.analystReviews.push({id:'analyst-2',subjectType:'mockup',ideaId:'dog-weather',action:'approve-mockup-for-developer-brief',note:'',submittedAt:at,submittedBy:'moderator'});const outcomes=await ingestAnalystReviews(store);expect(outcomes[0]).toEqual(expect.objectContaining({status:'processed',jobId:'product-development-handoff-dog-weather-analyst-2'}));expect(store.jobs[0]).toEqual(expect.objectContaining({agentId:'developer',status:'ready-for-review',humanGate:'implementation-scope-approval',implementationAuthorized:false,publicMutationAllowed:false}));});
});
